using Pautik;
using System;

public class EmptyInventoryComplaints 
{
    private static Tuple<string, string> DisappointedShopper => new Tuple<string, string>($"{GlobalFunctions.WhiteColorText("Depleted Shelves, Disappointed Shopper:")}", $"{GlobalFunctions.PartiallyTransparentText("Imagine walking into a store excited to explore and discover a plethora of products, only to be greeted by empty shelves and a sinking feeling of letdown. This lack of inventory reflects poorly on the store's ability to cater to its customers' needs and desires. A well-stocked and diverse inventory not only attracts shoppers but also ensures their satisfaction and loyalty. It's crucial for the management to recognize the impact of inadequate stock management and take prompt action to replenish their shelves, restore customer trust, and regain their competitive edge.")}");
    private static Tuple<string, string> LostOpportunities => new Tuple<string, string>($"{GlobalFunctions.WhiteColorText("Empty Shelves, Lost Opportunities:")}", $"{GlobalFunctions.PartiallyTransparentText("As a loyal customer, I had high expectations when I stepped into this store, hoping to find a wide variety of products to fulfill my shopping needs. Sadly, I was met with disappointment as I encountered empty shelves, devoid of the enticing choices I anticipated. An empty inventory not only frustrates customers but also hinders the store's potential for sales and growth. It's imperative for the management to address this issue promptly, invest in better stock management practices, and prioritize restocking efforts to create a vibrant shopping experience that keeps customers coming back.")}");
    private static Tuple<string, string> FrustratedByEmptyShelves => new Tuple<string, string>($"{GlobalFunctions.WhiteColorText("Frustrated by Empty Shelves:")}", $"{GlobalFunctions.PartiallyTransparentText("A well-stocked inventory is the backbone of any successful retail store. Unfortunately, this establishment failed to meet that basic requirement, leaving me disheartened and dissatisfied. The absence of products on the shelves not only limits customer choices but also raises questions about the store's ability to meet their demands. The management must recognize the significance of maintaining a robust inventory, take steps to improve their stock management practices, and ensure that customers are greeted with a diverse selection of items on their next visit.")}");
    private static Tuple<string, string> WhenExpectationsFallFlat => new Tuple<string, string>($"{GlobalFunctions.WhiteColorText("When Expectations Fall Flat:")}", $"{GlobalFunctions.PartiallyTransparentText("It's disheartening to walk into a store with specific shopping needs, only to find empty shelves staring back at you. This lack of inventory sends a message of neglect and disregard for customers' expectations. A well-stocked store not only offers convenience but also instills confidence in shoppers. It's crucial for the management to address the issue of empty shelves, invest in better stock management systems, and replenish their inventory promptly. Failure to do so risks alienating customers and driving them towards competitors.")}");
    private static Tuple<string, string> TheDisappointmentOfEmptyInventory => new Tuple<string, string>($"{GlobalFunctions.WhiteColorText("The Disappointment of an Empty Inventory:")}", $"{GlobalFunctions.PartiallyTransparentText("Nothing is more frustrating than entering a store with the intention to browse and purchase, only to be met with bare shelves and a sense of missed opportunities. An empty inventory not only reflects poorly on the store's reputation but also leaves customers feeling let down and inconvenienced. It's essential for the management to prioritize stock management, ensure consistent restocking, and maintain a vibrant inventory that meets the evolving needs of customers. By doing so, they can create a positive shopping experience and build lasting customer relationships.")}");

    public static Tuple<string, string>[] Texts = new Tuple<string, string>[]
    {
        DisappointedShopper,
        LostOpportunities,
        FrustratedByEmptyShelves,
        WhenExpectationsFallFlat,
        TheDisappointmentOfEmptyInventory
    };
}